using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using InpaintAR.Scripts.Util;
using Unity.Burst;
using Unity.Collections;
using Unity.Jobs;
using Unity.Mathematics;
using UnityEngine;

namespace InpaintAR.Scripts.Inpainting.Algorithms {
    // FMM Inpainting (Fast Marching Method)
    // See DOI 10.1080/10867651.2004.10487596
    public class FastMarchingAlgorithm : AbstractInpaintingAlgorithm {
        // Use bytes for Pixel State Decision, as its very memory efficient for the quest
        private const byte Known = 0; // From Source (outside mask)
        private const byte Band = 1; // On Boundary
        private const byte Inside = 2; // Inside Inpainting Region

        private const float MaxValue = 1e6f;
        private const float Eps = 1e-6f;
        
        // Radius for Neighborhood of Inpainting Reference Pixels
        // Reduced from 5 to 3 for optimization (49 vs 121 iterations per pixel)
        private const int Epsilon = 3;

        private int m_width;
        private int m_height;
        private int m_pixelCount;

        protected override Texture2D InpaintLogic(Texture2D source, HashSet<int> maskPixelIndices) {
            m_width = TextureUtility.GetImageWidth(source);
            m_height = TextureUtility.GetImageHeight(source);
            m_pixelCount = m_width * m_height;

            if (MInpaintedPixelBuffer == null || MInpaintedPixelBuffer.Length != m_pixelCount) {
                MInpaintedPixelBuffer = new Color32[m_pixelCount];
            }

            Array.Copy(MSourcePixelBuffer, MInpaintedPixelBuffer, m_pixelCount);

            Texture2D resultImage = new Texture2D(m_width, m_height, TextureFormat.RGBA32, false);
            
            InpaintFmmBurst(maskPixelIndices);

            resultImage.SetPixels32(MInpaintedPixelBuffer);
            resultImage.Apply();

            return resultImage;
        }

        // Implemented as Burst for high performance
        private void InpaintFmmBurst(HashSet<int> maskPixelIndices) {
            var distanceMap = new NativeArray<float>(m_pixelCount, Allocator.TempJob);
            var flags = new NativeArray<byte>(m_pixelCount, Allocator.TempJob);
            var pixels = new NativeArray<Color32>(MInpaintedPixelBuffer, Allocator.TempJob);
            
            // NativeParallelHashSet for O(1) lookup
            var maskIndicesSet = new NativeParallelHashSet<int>(maskPixelIndices.Count, Allocator.TempJob);
            var maskIndices = new NativeArray<int>(maskPixelIndices.Count, Allocator.TempJob);
            
            // Copy mask indices to native containers
            int idx = 0;
            foreach (var maskIdx in maskPixelIndices) {
                maskIndicesSet.Add(maskIdx);
                maskIndices[idx++] = maskIdx;
            }

            // Run initialization job with HashSet for O(1) lookup
            var initJob = new InitializeFmmJob {
                DistanceMap = distanceMap,
                Flags = flags,
                MaskIndicesSet = maskIndicesSet
            };
            initJob.Schedule(m_pixelCount, 64).Complete();
            maskIndicesSet.Dispose(); // Only needed for initialization due to O(1) Lookup
            
            var heap = new MinHeap(maskPixelIndices.Count * 4, Allocator.TempJob);
            var generations = new NativeArray<int>(m_pixelCount, Allocator.TempJob);
            
            BuildInitialBandWithHeap(ref heap, ref generations, ref flags, ref distanceMap, maskIndices, m_width, m_height);

            // Run FMM main loop with heap and generation tracking
            RunFmmWithHeap(ref heap, ref generations, ref flags, ref distanceMap, ref pixels, m_width, m_height);

            // Copy results back
            pixels.CopyTo(MInpaintedPixelBuffer);

            // Dispose native arrays
            distanceMap.Dispose();
            flags.Dispose();
            pixels.Dispose();
            maskIndices.Dispose();
            heap.Dispose();
            generations.Dispose();
        }

        // Optimization 4: Add generation tracking to skip stale heap entries
        [BurstCompile]
        private struct FmmNode : IComparable<FmmNode> {
            public float Distance;
            public int Index;
            public int Generation;

            public int CompareTo(FmmNode other) {
                return Distance.CompareTo(other.Distance);
            }
        }

        // MinHeap generated by Claude Opus
        [BurstCompile]
        private struct MinHeap : IDisposable {
            private NativeList<FmmNode> m_data;

            public int Length => m_data.Length;

            public MinHeap(int capacity, Allocator allocator) {
                m_data = new NativeList<FmmNode>(capacity, allocator);
            }

            public void Push(FmmNode node) {
                m_data.Add(node);
                SiftUp(m_data.Length - 1);
            }

            public FmmNode Pop() {
                var result = m_data[0];
                int lastIdx = m_data.Length - 1;
                m_data[0] = m_data[lastIdx];
                m_data.RemoveAt(lastIdx);
                if (m_data.Length > 0) SiftDown(0);
                return result;
            }

            private void SiftUp(int idx) {
                while (idx > 0) {
                    int parent = (idx - 1) / 2;
                    if (m_data[idx].Distance >= m_data[parent].Distance) break;
                    Swap(idx, parent);
                    idx = parent;
                }
            }

            private void SiftDown(int idx) {
                int count = m_data.Length;
                while (true) {
                    int smallest = idx;
                    int left = 2 * idx + 1;
                    int right = 2 * idx + 2;

                    if (left < count && m_data[left].Distance < m_data[smallest].Distance)
                        smallest = left;
                    if (right < count && m_data[right].Distance < m_data[smallest].Distance)
                        smallest = right;

                    if (smallest == idx) break;
                    Swap(idx, smallest);
                    idx = smallest;
                }
            }

            private void Swap(int a, int b) {
                (m_data[a], m_data[b]) = (m_data[b], m_data[a]);
            }

            public void Dispose() => m_data.Dispose();
        }

        // Optimization 1: Use NativeParallelHashSet for O(1) lookup instead of O(n) linear scan
        [BurstCompile]
        private struct InitializeFmmJob : IJobParallelFor {
            [WriteOnly] public NativeArray<float> DistanceMap;
            [WriteOnly] public NativeArray<byte> Flags;
            [ReadOnly] public NativeParallelHashSet<int> MaskIndicesSet;

            public void Execute(int index) {
                if (MaskIndicesSet.Contains(index)) {
                    Flags[index] = Inside;
                    DistanceMap[index] = MaxValue;
                } else {
                    Flags[index] = Known;
                    DistanceMap[index] = 0.0f;
                }
            }
        }

        [BurstCompile]
        private static void BuildInitialBandWithHeap(
            ref MinHeap heap,
            ref NativeArray<int> generations,
            ref NativeArray<byte> flags,
            ref NativeArray<float> distanceMap,
            NativeArray<int> maskIndices,
            int width, int height) {
            
            foreach (var idx in maskIndices) {
                int y = idx / width;
                int x = idx % width;

                // Check 8-connected neighbors
                for (int i = -1; i <= 1; i++) {
                    for (int j = -1; j <= 1; j++) {
                        if (i == 0 && j == 0) continue;

                        int nbY = y + i;
                        int nbX = x + j;

                        if (nbY < 0 || nbY >= height || nbX < 0 || nbX >= width) continue;

                        int nbIdx = nbY * width + nbX;

                        if (flags[nbIdx] == Band) continue;

                        // If the neighbor != Inside it's on the boundary
                        if (flags[nbIdx] != Known) continue;
                        flags[nbIdx] = Band;
                        distanceMap[nbIdx] = 0.0f;
                        generations[nbIdx] = 1;
                        heap.Push(new FmmNode { Distance = 0.0f, Index = nbIdx, Generation = 1 });
                    }
                }
            }
        }

        [BurstCompile]
        private static void RunFmmWithHeap(
            ref MinHeap heap,
            ref NativeArray<int> generations,
            ref NativeArray<byte> flags,
            ref NativeArray<float> distanceMap,
            ref NativeArray<Color32> pixels,
            int width, int height) {
            
            while (heap.Length > 0) {
                var node = heap.Pop();
                
                int idx = node.Index;
                
                // Skip if this is a stale entry (generation mismatch)
                if (node.Generation != generations[idx]) continue;
                
                // Skip if already processed
                if (flags[idx] == Known) continue;
                
                flags[idx] = Known;
                
                int y = idx / width;
                int x = idx % width;

                // All Neighbors
                for (int i = -1; i <= 1; i++) {
                    for (int j = -1; j <= 1; j++) {
                        if (i == 0 && j == 0) continue;

                        int nbY = y + i;
                        int nbX = x + j;

                        if (nbY < 0 || nbY >= height || nbX < 0 || nbX >= width) continue;

                        int nbIdx = nbY * width + nbX;

                        if (flags[nbIdx] != Known) {
                            // Inpaint if inside
                            if (flags[nbIdx] == Inside) {
                                InpaintPixelBurst(ref pixels, ref distanceMap, ref flags, nbY, nbX, width, height);
                            }

                            // Solve eikonal
                            float newDist = SolveEikonalQuadrants(ref distanceMap, ref flags, nbY, nbX, width, height);

                            if (newDist < distanceMap[nbIdx]) {
                                distanceMap[nbIdx] = newDist;
                                // Old entries with lower generation will be skipped
                                generations[nbIdx]++;
                                heap.Push(new FmmNode { Distance = newDist, Index = nbIdx, Generation = generations[nbIdx] });
                            }

                            if (flags[nbIdx] == Inside) {
                                flags[nbIdx] = Band;
                            }
                        }
                    }
                }
            }
        }


        [BurstCompile]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static float SolveEikonalQuadrants(
            ref NativeArray<float> distanceMap,
            ref NativeArray<byte> flags,
            int y, int x, int width, int height) {
            
            float sol1 = MaxValue, sol2 = MaxValue, sol3 = MaxValue, sol4 = MaxValue;

            if (y - 1 >= 0 && x - 1 >= 0) {
                sol1 = SolveEikonal(ref distanceMap, ref flags, y - 1, x, y, x - 1, width, height);
            }
            if (y - 1 >= 0 && x + 1 < width) {
                sol2 = SolveEikonal(ref distanceMap, ref flags, y - 1, x, y, x + 1, width, height);
            }
            if (y + 1 < height && x - 1 >= 0) {
                sol3 = SolveEikonal(ref distanceMap, ref flags, y + 1, x, y, x - 1, width, height);
            }
            if (y + 1 < height && x + 1 < width) {
                sol4 = SolveEikonal(ref distanceMap, ref flags, y + 1, x, y, x + 1, width, height);
            }

            return math.min(math.min(sol1, sol2), math.min(sol3, sol4));
        }

        [BurstCompile]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static float SolveEikonal(
            ref NativeArray<float> distanceMap,
            ref NativeArray<byte> flags,
            int y1, int x1, int y2, int x2,
            int width, int height) {
            
            if (y1 < 0 || y1 >= height || x1 < 0 || x1 >= width) return MaxValue;
            if (y2 < 0 || y2 >= height || x2 < 0 || x2 >= width) return MaxValue;

            int idx1 = y1 * width + x1;
            int idx2 = y2 * width + x2;

            byte flag1 = flags[idx1];
            byte flag2 = flags[idx2];

            if (flag1 == Known) {
                if (flag2 == Known) {
                    float t1 = distanceMap[idx1];
                    float t2 = distanceMap[idx2];
                    float d = 2.0f - (t1 - t2) * (t1 - t2);

                    if (d > 0.0f) {
                        float r = math.sqrt(d);
                        float s = (t1 + t2 - r) / 2;

                        if (s >= t1 && s >= t2) {
                            return s;
                        }

                        s += r;
                        if (s >= t1 && s >= t2) {
                            return s;
                        }

                        return MaxValue;
                    }
                } else {
                    return 1.0f + distanceMap[idx1];
                }
            }

            if (flag2 == Known) {
                return 1.0f + distanceMap[idx2];
            }

            return MaxValue;
        }

        [BurstCompile]
        private static void InpaintPixelBurst(
            ref NativeArray<Color32> pixels,
            ref NativeArray<float> distanceMap,
            ref NativeArray<byte> flags,
            int y, int x, int width, int height) {
            
            int centerIdx = y * width + x;
            
            // Gradient of T at [y, x]
            float2 gradT = ComputeGradientTBurst(ref distanceMap, y, x, width, height);

            float denominator = 0f;
            float numR = 0f, numG = 0f, numB = 0f;

            // Iterate through epsilon neighborhood
            for (int i = y - Epsilon; i <= y + Epsilon; i++) {
                for (int j = x - Epsilon; j <= x + Epsilon; j++) {
                    if (i < 0 || i >= height || j < 0 || j >= width) continue;
                    if (i == y && j == x) continue;

                    int nbIdx = i * width + j;
                    if (flags[nbIdx] != Known) continue;

                    float2 vector = new float2(y - i, x - j);
                    float distSq = vector.x * vector.x + vector.y * vector.y;
                    if (distSq > Epsilon * Epsilon) continue;

                    // Euclidean distance
                    float normVector = math.sqrt(distSq);
                    if (normVector < Eps) normVector = Eps;

                    // Directional weight: only consider upstream pixels
                    // For information propagate into the inpainting region
                    float dir = math.dot(gradT, vector) / normVector;
                    dir = math.max(0f, dir);
                    if (dir < Eps) continue;  // Skip pixels with no contribution

                    // Geometric distance weight: 1/d²
                    float dist = 1f / distSq;
                    
                    // Level set weight: prefer pixels at similar distance from boundary
                    float lev = 1f / (1f + math.abs(distanceMap[centerIdx] - distanceMap[nbIdx]));
                    
                    float w = dir * dist * lev;

                    Color32 color = pixels[nbIdx];
                    
                    // I(p) = Σ w(q) · [I(q) + ∇I(q)·(p-q)] / Σ w(q)
                    ComputeGradientIBurst(ref pixels, ref flags, i, j, width, height, out var gradIy, out var gradIx);
                    
                    // (p-q)
                    float2 pq = -vector;
                    
                    // ∇I(q)·(p-q) = gradIY*(p-q).y + gradIX*(p-q).x for each channel
                    numR += w * (color.r + gradIy.x * pq.x + gradIx.x * pq.y);
                    numG += w * (color.g + gradIy.y * pq.x + gradIx.y * pq.y);
                    numB += w * (color.b + gradIy.z * pq.x + gradIx.z * pq.y);
                    denominator += w;
                }
            }

            if (denominator > Eps) {
                pixels[centerIdx] = new Color32(
                    (byte)math.clamp(numR / denominator, 0, 255),
                    (byte)math.clamp(numG / denominator, 0, 255),
                    (byte)math.clamp(numB / denominator, 0, 255),
                    255
                );
            }
        }
        
        [BurstCompile]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static void ComputeGradientIBurst(
            ref NativeArray<Color32> pixels,
            ref NativeArray<byte> flags,
            int y, int x, int width, int height,
            out float4 gradY, out float4 gradX) {
            
            gradY = float4.zero;
            gradX = float4.zero;
            
            int idx = y * width + x;
            
            // Y gradient (vertical) using central differences where possible
            if (y > 0 && y < height - 1) {
                int idxUp = (y - 1) * width + x;
                int idxDown = (y + 1) * width + x;
                switch (flags[idxUp]) {
                    case Known when flags[idxDown] == Known: {
                        Color32 up = pixels[idxUp];
                        Color32 down = pixels[idxDown];
                        gradY = new float4(down.r - up.r, down.g - up.g, down.b - up.b, down.a - up.a) / 2;
                        break;
                    }
                    case Known: {
                        Color32 cur = pixels[idx];
                        Color32 up = pixels[idxUp];
                        gradY = new float4(cur.r - up.r, cur.g - up.g, cur.b - up.b, cur.a - up.a);
                        break;
                    }
                    default: {
                        if (flags[idxDown] == Known) {
                            Color32 cur = pixels[idx];
                            Color32 down = pixels[idxDown];
                            gradY = new float4(down.r - cur.r, down.g - cur.g, down.b - cur.b, down.a - cur.a);
                        }

                        break;
                    }
                }
            } else if (y > 0) {
                int idxUp = (y - 1) * width + x;
                if (flags[idxUp] == Known) {
                    Color32 cur = pixels[idx];
                    Color32 up = pixels[idxUp];
                    gradY = new float4(cur.r - up.r, cur.g - up.g, cur.b - up.b, cur.a - up.a);
                }
            } else if (y < height - 1) {
                int idxDown = (y + 1) * width + x;
                if (flags[idxDown] == Known) {
                    Color32 cur = pixels[idx];
                    Color32 down = pixels[idxDown];
                    gradY = new float4(down.r - cur.r, down.g - cur.g, down.b - cur.b, down.a - cur.a);
                }
            }
            
            // X gradient (horizontal) using central differences where possible
            if (x > 0 && x < width - 1) {
                int idxLeft = y * width + x - 1;
                int idxRight = y * width + x + 1;
                switch (flags[idxLeft]) {
                    case Known when flags[idxRight] == Known: {
                        Color32 left = pixels[idxLeft];
                        Color32 right = pixels[idxRight];
                        gradX = new float4(right.r - left.r, right.g - left.g, right.b - left.b, right.a - left.a) / 2;
                        break;
                    }
                    case Known: {
                        Color32 cur = pixels[idx];
                        Color32 left = pixels[idxLeft];
                        gradX = new float4(cur.r - left.r, cur.g - left.g, cur.b - left.b, cur.a - left.a);
                        break;
                    }
                    default: {
                        if (flags[idxRight] == Known) {
                            Color32 cur = pixels[idx];
                            Color32 right = pixels[idxRight];
                            gradX = new float4(right.r - cur.r, right.g - cur.g, right.b - cur.b, right.a - cur.a);
                        }

                        break;
                    }
                }
            } else if (x > 0) {
                int idxLeft = y * width + x - 1;
                if (flags[idxLeft] != Known) return;
                Color32 cur = pixels[idx];
                Color32 left = pixels[idxLeft];
                gradX = new float4(cur.r - left.r, cur.g - left.g, cur.b - left.b, cur.a - left.a);
            } else if (x < width - 1) {
                int idxRight = y * width + x + 1;
                if (flags[idxRight] != Known) return;
                Color32 cur = pixels[idx];
                Color32 right = pixels[idxRight];
                gradX = new float4(right.r - cur.r, right.g - cur.g, right.b - cur.b, right.a - cur.a);
            }
        }

        [BurstCompile]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static float2 ComputeGradientTBurst(
            ref NativeArray<float> distanceMap,
            int y, int x, int width, int height) {
            
            float gradY = 0f, gradX = 0f;

            switch (y) {
                case > 0 when y < height - 1:
                    gradY = (distanceMap[(y + 1) * width + x] - distanceMap[(y - 1) * width + x]) / 2;
                    break;
                case > 0:
                    gradY = distanceMap[y * width + x] - distanceMap[(y - 1) * width + x];
                    break;
                default: {
                    if (y < height - 1) {
                        gradY = distanceMap[(y + 1) * width + x] - distanceMap[y * width + x];
                    }

                    break;
                }
            }

            switch (x) {
                case > 0 when x < width - 1:
                    gradX = (distanceMap[y * width + x + 1] - distanceMap[y * width + x - 1]) / 2;
                    break;
                case > 0:
                    gradX = distanceMap[y * width + x] - distanceMap[y * width + x - 1];
                    break;
                default: {
                    if (x < width - 1) {
                        gradX = distanceMap[y * width + x + 1] - distanceMap[y * width + x];
                    }

                    break;
                }
            }

            return new float2(gradY, gradX);
        }
    }
}
